-- liquibase formatted sql
-- changeset Natalia:4
create table if not exists public.recommendations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary    key,
    product_id UUID NOT Null,
    product_name    CHARACTER    VARYING(255) NOT NULL,
    product_text text NOT NULL
    );
create table if not exists public.rules
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY  primary    key,
    query   CHARACTER  VARYING (255) NOT NULL,
    arguments CHARACTER  VARYING (255) NOT NULL,
    negate BOOLEAN NOT NULL,
    recommendation_id BIGINT NOT NULL,
    FOREIGN KEY (recommendation_id) REFERENCES recommendations(id)
    on delete cascade
    );